[package]
name = "sign_perf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.7.2"
sha2 = "0.10.6"
rand = "0.8.4"
p256 = { version = "0.11", features = ["pem"] }
ecdsa = "0.14.8"