[package]
name = "decrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

crypto="0.4.0"
cbc = "0.1.2"
aes = "0.8.1"