package main

import (
	"math/rand"
)

// build a flirt sentence as a string from a list of words generated by the flirt generator
// generate the words for a flirt sentence
func flirt_generator() []string {
	// generate a list of words
	words := []string{}
	// generate a random number of words
	num_words := rand.Intn(10) + 1
	// generate the words
	for i := 0; i < num_words; i++ {
		words = append(words, flirt_word())
	}
	return words
}

// generate a list of constant strings with words that can be used in a flirt sentence
func flirt_word() string {
	// generate a random number
	rand_num := rand.Intn(100)
	// generate a word based on the random number
	if rand_num < 10 {
		return "I"

	} else if rand_num < 20 {
		return "you"

	} else if rand_num < 30 {
		return "like"

	} else if rand_num < 40 {
		return "love"

	} else if rand_num < 50 {
		return "hate"

	} else if rand_num < 60 {
		return "want"

	} else if rand_num < 70 {
		return "need"

	} else if rand_num < 80 {
		return "desire"

	} else if rand_num < 90 {
		return "am"

	} else if rand_num < 100 {
		return "are"

	} else {
		return "ERROR"
	}
}

func build_sentence(words []string) string {
	sentence := ""
	for _, word := range words {
		sentence += word + " "
	}
	return sentence
}

// generate a flirt sentence
func flirt() string {
	// generate a sentence from the flirt generator
	words := flirt_generator()
	// build the sentence
	sentence := build_sentence(words)
	return sentence
}
